test

diff --git a/.github/workflows/static_build_packaging.yml b/.github/workflows/static_build_packaging.yml
--- a/.github/workflows/static_build_packaging.yml
+++ b/.github/workflows/static_build_packaging.yml
@@ -33,25 +33,25 @@ concurrency:
 
 jobs:
   static_build_packaging:
-    name: 'static_build_packaging (${{ matrix.arch }})'
+    name: 'static_build_packaging_(${{ matrix.arch }})'
 
     # Run on push to the 'master' and release branches of tarantool/tarantool
     # or on pull request if the 'full-ci' or 'static-build-ci' label is set.
-    if: github.repository == 'tarantool/tarantool' &&
-        ( github.event_name != 'pull_request' ||
-          contains(github.event.pull_request.labels.*.name, 'full-ci') ||
-          contains(github.event.pull_request.labels.*.name, 'static-build-ci') )
+    # if: github.repository == 'tarantool/tarantool' &&
+    #     ( github.event_name != 'pull_request' ||
+    #       contains(github.event.pull_request.labels.*.name, 'full-ci') ||
+    #       contains(github.event.pull_request.labels.*.name, 'static-build-ci') )
 
-    runs-on: ${{ matrix.runner }}
+    runs-on: ubuntu-latest
 
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - runner: ubuntu-20.04-self-hosted
-            arch: x86_64
-          - runner: graviton
-            arch: aarch64
+    # strategy:
+    #   fail-fast: false
+    #   matrix:
+    #     include:
+    #       - runner: ubuntu-20.04-self-hosted
+    #         arch: x86_64
+    #       - runner: graviton
+    #         arch: aarch64
 
     steps:
       - name: Prepare checkout
@@ -81,16 +81,16 @@ jobs:
           bot-token: ${{ secrets.VKTEAMS_BOT_TOKEN }}
 
   static_build_testing:
-    name: 'static_build_testing (${{ matrix.sys-arch }}) on ${{ matrix.os }}'
+    name: 'static_build_testing_(${{ matrix.sys-arch }})_${{ matrix.os }}'
 
     # Run on push to the 'master' and release branches of tarantool/tarantool
     # or on pull request if the 'full-ci' or 'static-build-ci' label is set.
-    if: github.repository == 'tarantool/tarantool' &&
-        ( github.event_name != 'pull_request' ||
-          contains(github.event.pull_request.labels.*.name, 'full-ci') ||
-          contains(github.event.pull_request.labels.*.name, 'static-build-ci') )
+    # if: github.repository == 'tarantool/tarantool' &&
+    #     ( github.event_name != 'pull_request' ||
+    #       contains(github.event.pull_request.labels.*.name, 'full-ci') ||
+    #       contains(github.event.pull_request.labels.*.name, 'static-build-ci') )
 
-    runs-on: [ self-hosted, Linux, '${{ matrix.sys-arch }}', regular ]
+    runs-on: ubuntu-latest
 
     needs: static_build_packaging
 
@@ -104,36 +104,36 @@ jobs:
               dpkg -i tarantool*$(dpkg --print-architecture).deb
             install-requires: |
               apt update && apt -y install python3-pip && pip install -r requirements.txt
-          - os: ubuntu-jammy
-            sys-arch: aarch64
-            install-tarantool: |
-              dpkg -i tarantool*$(dpkg --print-architecture).deb
-            install-requires: |
-              apt update && apt -y install python3-pip && pip install -r requirements.txt
+          # - os: ubuntu-jammy
+          #   sys-arch: aarch64
+          #   install-tarantool: |
+          #     dpkg -i tarantool*$(dpkg --print-architecture).deb
+          #   install-requires: |
+          #     apt update && apt -y install python3-pip && pip install -r requirements.txt
           - os: debian-bullseye
             sys-arch: x86_64
             install-tarantool: |
               dpkg -i tarantool*$(dpkg --print-architecture).deb
             install-requires: |
               apt update && apt -y install python3-pip && pip install -r requirements.txt
-          - os: debian-bullseye
-            sys-arch: aarch64
-            install-tarantool: |
-              dpkg -i tarantool*$(dpkg --print-architecture).deb
-            install-requires: |
-              apt update && apt -y install python3-pip && pip install -r requirements.txt
+          # - os: debian-bullseye
+          #   sys-arch: aarch64
+          #   install-tarantool: |
+          #     dpkg -i tarantool*$(dpkg --print-architecture).deb
+          #   install-requires: |
+          #     apt update && apt -y install python3-pip && pip install -r requirements.txt
           - os: fedora-36
             sys-arch: x86_64
             install-tarantool: |
               dnf -y localinstall tarantool*$(uname -m).rpm
             install-requires: |
               dnf -y install python3-pip e2fsprogs && pip install -r requirements.txt
-          - os: fedora-36
-            sys-arch: aarch64
-            install-tarantool: |
-              dnf -y localinstall tarantool*$(uname -m).rpm
-            install-requires: |
-              dnf -y install python3-pip e2fsprogs && pip install -r requirements.txt
+          # - os: fedora-36
+          #   sys-arch: aarch64
+          #   install-tarantool: |
+          #     dnf -y localinstall tarantool*$(uname -m).rpm
+          #   install-requires: |
+          #     dnf -y install python3-pip e2fsprogs && pip install -r requirements.txt
 
     container:
       image: packpack/packpack:${{ matrix.os }}
@@ -155,7 +155,7 @@ jobs:
         with:
           fetch-depth: 0
           submodules: recursive
-      - uses: ./.github/actions/environment
+#      - uses: ./.github/actions/environment
       - name: Download built artifacts
         uses: actions/download-artifact@v3
         with:
@@ -171,7 +171,7 @@ jobs:
         run: ${{ matrix.install-requires }}
         working-directory: test-run
       - name: Run tests
-        run: ./test-run.py --force --builddir ../build --executable /usr/bin/tarantool
+        run: ./test-run.py --force --builddir ../build --executable /usr/bin/tarantool || true
         working-directory: test
       - name: Send VK Teams message on failure
         if: failure()
@@ -184,12 +184,14 @@ jobs:
 
     # Run on push to the 'master' and release branches of tarantool/tarantool
     # or on pull request if the 'full-ci' or 'static-build-ci' label is set.
-    if: github.repository == 'tarantool/tarantool' &&
-        ( github.event_name != 'pull_request' ||
-          contains(github.event.pull_request.labels.*.name, 'full-ci') ||
-          contains(github.event.pull_request.labels.*.name, 'static-build-ci') )
+    # if: github.repository == 'tarantool/tarantool' &&
+    #     ( github.event_name != 'pull_request' ||
+    #       contains(github.event.pull_request.labels.*.name, 'full-ci') ||
+    #       contains(github.event.pull_request.labels.*.name, 'static-build-ci') )
 
-    runs-on: ubuntu-20.04-self-hosted
+    runs-on: ubuntu-latest
+
+    needs: static_build_testing
 
     steps:
       - name: Prepare checkout
